%% PSO / e-PSA Testbench Info Collector (struct + timestamped filename + confirmation popup)
% Creates a struct with all relevant testbench information, generates a
% date-time based filename, and launches a popup window for user confirmation.

function test_info = test_info()

    %% --------- Default values (edit as you like) ----------
    test_info = struct( ...
        'battery', struct( ...
            'num_cells', 4, ...
            'capacity_mAh', 2200, ...
            'charge_state', "Full" ...   % e.g., "Full", "Storage", "Partial", "Unknown"
        ), ...
        'esc', struct( ...
            'model', "ESC-Model", ...
            'configuration', "Default" ...
        ), ...
        'motor', struct( ...
            'model', "Motor-Model", ...
            'kv', 650 ...
        ), ...
        'propeller', struct( ...
            'model', "Prop-Model", ...
            'size_in', "15x7.5", ...
            'rotation', "CW", ...        % "CW" or "CCW"
            'balanced', true ...
        ), ...
        'test_data', struct( ...
            'date', datetime("now"), ...
            'filename', "" ...
        ), ...
        'firmware', struct( ...
            'version', "v0.0.0" ...
        ) ...
    );

    %% --------- Create a safe timestamp filename ----------
    % Example: epsa_test_2026-01-12_16-34-08
    ts = datetime("now");
    ts_str = datestr(ts, "yyyy-mm-dd_HH-MM-SS");  % safe for Windows/Linux filenames
    test_info.test_data.filename = "epsa_test_" + string(ts_str);

    %% --------- Build prompts for a popup dialog ----------
    prompt = { ...
        'Battery: # Cells', ...
        'Battery: Capacity (mAh)', ...
        'Battery: Charge (e.g., Full/Storage/Partial/Unknown)', ...
        'ESC: Model', ...
        'ESC: Configuration', ...
        'Motor: Model', ...
        'Motor: KV', ...
        'Propeller: Model', ...
        'Propeller: Size (in) (e.g., 15x7.5)', ...
        'Propeller: Rotation (CW/CCW)', ...
        'Propeller: Balanced (Y/N)', ...
        'Firmware: Version', ...
        'Test: Filename (auto-generated; you may edit)' ...
    };

    defaults = { ...
        num2str(test_info.battery.num_cells), ...
        num2str(test_info.battery.capacity_mAh), ...
        char(test_info.battery.charge_state), ...
        char(test_info.esc.model), ...
        char(test_info.esc.configuration), ...
        char(test_info.motor.model), ...
        num2str(test_info.motor.kv), ...
        char(test_info.propeller.model), ...
        char(test_info.propeller.size_in), ...
        char(test_info.propeller.rotation), ...
        ternary(test_info.propeller.balanced, 'Y', 'N'), ...
        char(test_info.firmware.version), ...
        char(test_info.test_data.filename) ...
    };

    dlg_title = 'Confirm Testbench Information (e-PSA)';
    dims = [1 60];

    %% --------- Launch popup and parse results ----------
    answer = inputdlg(prompt, dlg_title, dims, defaults);

    if isempty(answer)
        error('User cancelled. No test_info returned.');
    end

    % Parse and validate (lightweight)
    test_info.battery.num_cells    = max(1, round(str2double(answer{1})));
    test_info.battery.capacity_mAh = max(0, round(str2double(answer{2})));
    test_info.battery.charge_state = string(strtrim(answer{3}));

    test_info.esc.model           = string(strtrim(answer{4}));
    test_info.esc.configuration   = string(strtrim(answer{5}));

    test_info.motor.model         = string(strtrim(answer{6}));
    test_info.motor.kv            = max(0, round(str2double(answer{7})));

    test_info.propeller.model     = string(strtrim(answer{8}));
    test_info.propeller.size_in   = string(strtrim(answer{9}));

    rot = upper(string(strtrim(answer{10})));
    if rot ~= "CW" && rot ~= "CCW"
        rot = "CW"; % fallback
    end
    test_info.propeller.rotation  = rot;

    bal = upper(string(strtrim(answer{11})));
    test_info.propeller.balanced  = (bal == "Y" || bal == "YES" || bal == "TRUE" || bal == "1");

    test_info.firmware.version    = string(strtrim(answer{12}));

    test_info.test_data.date      = datetime("now"); % keep actual confirmation time
    test_info.test_data.filename  = string(strtrim(answer{13}));

    %% --------- Final confirmation dialog (summary) ----------
    summary = sprintf([ ...
        "Battery: %dS, %d mAh, Charge: %s\n" + ...
        "ESC: %s (%s)\n" + ...
        "Motor: %s, %d KV\n" + ...
        "Prop: %s, %s, %s, Balanced: %s\n" + ...
        "Firmware: %s\n" + ...
        "Date: %s\n" + ...
        "Filename: %s\n"], ...
        test_info.battery.num_cells, ...
        test_info.battery.capacity_mAh, ...
        test_info.battery.charge_state, ...
        test_info.esc.model, ...
        test_info.esc.configuration, ...
        test_info.motor.model, ...
        test_info.motor.kv, ...
        test_info.propeller.model, ...
        test_info.propeller.size_in, ...
        test_info.propeller.rotation, ...
        ternary(test_info.propeller.balanced, "Y", "N"), ...
        test_info.firmware.version, ...
        datestr(test_info.test_data.date, "yyyy-mm-dd HH:MM:SS"), ...
        test_info.test_data.filename);

    choice = questdlg(summary, 'Confirm?', 'OK', 'Edit', 'Cancel', 'OK');

    switch choice
        case 'OK'
            % proceed
        case 'Edit'
            % restart once
            test_info = epsa_collect_test_info();
        otherwise
            error('User cancelled. No test_info returned.');
    end
end

%% ---- small helper ----
function out = ternary(cond, a, b)
    if cond, out = a; else, out = b; end
end
